# Generated by Django 2.1.3 on 2018-12-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RepoShulita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='email',
            new_name='descripcion',
        ),
    ]
